name: startate
description: State manager and Dependency Injection for Flutter
version: 5.1.0
homepage: https://github.com/TFSThiagoBR98/startate

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ">=0.5.0 <2.0.0"

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
